@startuml

left to right direction

:Cliente: as Cliente
:Restaurante: as Restaurante

rectangle {
Cliente -- (Mostrar menú)
Cliente -- (Pedir comida)
(Mostrar menú) -- Restaurante
}

Restaurante -- (Entregar comida)
@enduml