@startuml

(SacarDinero) <.."<<Extend>>" (Retener tarjeta)
note as N1
 <u>Descripcion__________________________________________________________________________________________________________________</u>
  condición:
    {historia sospechosa}
  punto de extensión:
    solicitud hecha
end note


N1 -- (SacarDinero)
@enduml